### ISSUE TITLE
Implement Visual Enhancements (CSS)

### ISSUE THREAD

**Issue by mchisolm0** [HCHS-Chisolm/typhoon-game#8]
### Issue: Implement Visual Enhancements (CSS)

**Description:**
The game currently has a basic visual style. This issue aims to improve the visual appeal of the game using CSS.

**Implementation Steps:**

1.  **CSS (style.css):**
    *   Experiment with different fonts, colors, and background images.
    *   Add hover effects to the cells.
    *   Use CSS transitions and animations to make the game more engaging.
    *   Consider using a CSS framework like Bootstrap or Tailwind CSS for a more polished look.

**Example CSS:**

```css
body {
  background-color: #222;
  color: #fff;
  font-family: 'Arial', sans-serif;
}

.cell {
  background-color: #444;
  color: #fff;
  transition: background-color 0.2s ease-in-out;
}

.cell:hover {
  background-color: #666;
}

.revealed {
  background-color: #888;
}
```
## Acceptance Criteria:
- The game has a visually appealing and engaging design.
- The CSS is well-organized and maintainable.

**Comment by CodingCarda** [comment]
I'll do this. o/

**Comment by mchisolm0** [comment]
For example, "Typhoon" overflows the box.

**Comment by mchisolm0** [comment]
Also, once the hamburger menu PR gets merged in, we will want to also see how we want to update the CSS for the all those styles, too.

**Comment by CodingCarda** [comment]
@ANOG0 I am planning to animate a cell when it is revealed to be a certain thing (i.e. "Bomb", "Poison", "Red Cross" etc.) though I am confused on how I can do so when the options are supposed to be random and how I would do so in CSS.

Example: Bomb when chosen will infinitely flash orange, yellow, orange, red. The text will 'shake' and increase and decrease in font size once.

**Comment by ANOG0** [comment]
Currently at lunch, but ill get back to as soon as possible

**Comment by mchisolm0** [comment]
No rush. We think we have a solution. We think we are going to add an if/else statement in the `script.js` directly under where it adds the `value` from the array into the cell's text content.

```js
cell.textContent = value;

// New code
if(value === "Typhoon) {
  cell.classList.add("typhoon");
} else if ( /* Other conditions */ ) {
  // Add other classes
} // Other else if statements

// Continue old code
cell.classList.add("revealed");
```

**Comment by mchisolm0** [comment]
And then we will just have a style ruleset for the elements with the `revealed` class AND the `typhoon` class, etc. Do you remember the syntax for that?

**Comment by ANOG0** [comment]
I feel it'd be better if you used ```cell.id``` instead of ```cell.classList``` (just because it's easier to implement and less confusing going forward, please correct me if im wrong on that though), 

but in CSS the syntax would be:
```css
/* If using cell.id */|
#revealed {

}
/* If using classes */
.revealed {

}
```

**Comment by ANOG0** [comment]
Also I have figured out how to create flickering effects:

So first of all, in your explosion CSS class/id you need to define 3 things

- ```animation-iteration-count``` (Optional) (the amount of times the animation will loop)
- ```animation-name``` (how you will call on the animation later)
- ```animation-duration``` (how long each animation sequence lasts)

Here is how you would define them:
```css
#bomb {
  animation-iteration-count: infinite;
  animation-name: flicker;
  animation-duration: 2s;
}
```

Next, you will need to define the keyframes _this is why you need to define the animation name previously._
This is not defined like other CSS elements, instead it is defined as so:

```css
@keyframes flicker {

}
```

After that we will define how the animation will play out, using percentages we will make 0% and 100% the same, only changing the percentages inbetween (unless you are not looping the animation) in order to do so you have to frame it like this:
```css
@keyframes flicker {
  0%   {background-color: red;}
  50%  {background-color: yellow;}
  100% {background-color: red;}
}
```

note how it is the percentage first, and then wrapped in curly brackets it is a CSS property. This is a pretty flexible system so if you want to create shaking text you could adjust the padding on the text (look up documentation if you do not know how to do this), or you could create the typhoon effect by causing the animation to play only once (if the animation is playing only once, make sure 100% is the final color you want the background/property to be, or else it'll look back.)

If you need any more help then please contact me and i'll try and respond as soon as i can.
